// 开票记录获取
export const COMMON_INVOICE_RECORD = 'COMMON_INVOICE_RECORD'

// 商户信息
export const COMMON_CUSTOMER = 'COMMON_CUSTOMER'

// 生成订单
export const COMMON_CUSTOMER_ORDER = 'COMMON_CUSTOMER_ORDER'



