// 查询订单
export const INVOICE_ElECTRIC_ORDER = 'INVOICE_ElECTRIC_ORDER'
//开票记录
export const INVOICE_ElECTRIC_RECORD = 'INVOICE_ElECTRIC_RECORD'
// 开电子发票
export const INVOICE_ElECTRIC_PAYMENT = 'INVOICE_ElECTRIC_PAYMENT'

